### PR TITLE
#1 Issue resolved StopWatch

### PR DESCRIPTION
**Pull request by vivekBoii**
Thank you once again

### CODE REVIEW

**Comment by swagatmitra-b** [comment]
Screenshot2

**Comment by swagatmitra-b** [comment]
Screenshot2

**Comment by vivekBoii** [comment]
No worries sir I am confident enough to contribute and make more than 10 pr.

Thanks for your advice, may God watch over you

**Comment by swagatmitra-b** [comment]
Alright then. I'll be merging this PR. Good luck with your contributions!

**Pull request merged**
