### PR TITLE
Fixed issue #4  line break issue 

### PR DESCRIPTION
**Pull request by mhamzanadeem**
I am participating in hacktoberfest 2023 .  I want my contribution to be counted in this event. 
If my contribution  is not up to mark . i will review my  contribution :)

### CODE REVIEW

**Comment by swagatmitra-b** [comment]
Looks good to me 👍

**Comment by swagatmitra-b** [comment]
Screenshot2

**Comment by mhamzanadeem** [comment]
:(  .  Ok now merge it

**Comment by swagatmitra-b** [comment]
Please make another pull request with the same changes since this will not be considered for hacktoberfest as per the rules

**Comment by mhamzanadeem** [comment]
ok . i will make new pull request

**Pull request closed without merging**
